version: '3'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  auth-service:
    image: auth-service
    build:
      context: ./services/Auth-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  product-service:
    image: product-service
    build:
      context: ./services/Product-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  storage-service:
    image: storage-service
    build:
      context: ./services/Storage-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  order-service:
    image: order-service
    build:
      context: ./services/Order-Service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  gateway:
    image: gateway
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8080:8080"
    networks:
      - static-network
    depends_on:
      - consul-server


  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    networks:
      - static-network

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16