export const LOGIN_START = `LOGIN_START`;
export const SET_LOGGED_USER = `SET_LOGGED_USER`
export const LOGIN_FAILED = `LOGIN_FAILED`;

export const LOGOUT = `LOGOUT`;

export const CREATE_PRODUCT_START = `CREATE_PRODUCT_START`;
export const PRODUCT_CREATED = `PRODUCT_CREATED`;
export const CREATE_PRODUCT_FAILED = `CREATE_PRODUCT_FAILED`